### PR TITLE
add `append` to ncdatasets write

### PR DESCRIPTION
**Pull request by kongdd**
With the parameter `append`, multiple variables can be saved into the same file.

### CODE REVIEW

**Comment by kongdd** [comment]
Still have an issue. The `mode` `a` can not overwritte an existing variable, just add new one. 
But this issue also can be ignored and solved by setting `append = false`.

**Comment by rafaqz** [comment]
I guess that means we need to set `append=false` as the default, or this is a breaking change.

Otherwise this is great, just add `append` to the keywords docs and its good to go.

**Comment by kongdd** [comment]
`append=true` is desired for me. But I am not sure for others. So decision on you.

**Comment by rafaqz** [comment]
Currently writing a file a second time will work, but with this change it wont - so existing scripts will break - I know some of mine will!

We should as much as possible try not to break existing scripts with new features... so lets set it to `false`, and you can choose to set it to `true`. We also can revisit this in future if everyone uses `append=true`.

**Comment by kongdd** [comment]
Agree.

**Comment by rafaqz** [comment]
Thanks! Sorry I'm slow on merging Im insanely busy currently.

**Comment by kongdd** [comment]
No worries. I am trying to bump DiskArrays to v0.3. But it not work. The last commit about `DiskArrays` should be removed.
The others scripts have been passed test.

**Comment by rafaqz** [comment]
Yeah there are some problems with the changes to DiskArrays.jl in v0.3 I have been slowly fixing. Hopefully get that finished soon.

**Pull request merged**
