### PR TITLE
Small fix: Ensure that dates is always defined

### PR DESCRIPTION
**Pull request by jguerber**
Hey,
I got some errors while using `date` as an `AbstractArray`, this small reorganization should fix it.

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks! But this needs a test of whatever it is that didn't work before that worksgiven this change. 

Also including your code and the error in the description would help us understand why we need this change

**Comment by jguerber** [comment]
Yeah sorry that was a bit short :sweat_smile:

In RasterSeries construction, for raster data sources that use a `date` argument, using `date` as an `AbstractArray` allows to fetch only certain dates and not the whole sequence of dates in between. However, it seemed a bit broken:
 
```julia
ser = RasterSeries(AWAP, :solar; date = [Date(2001,1,1), Date(2001,1,5)]) # throws UndefVarError: dates not defined
```
This was caused by the structure of the `if` blocks inside `RasterSeries`, the fix ensures that `Ti(dates,...)` is called only in cases where `dates` is defined. Now it works correctly:

```julia
julia>ser = RasterSeries(AWAP, :solar; date = [Date(2001,1,1), Date(2001,1,5)])
2-element RasterSeries{Raster,1} with dimensions: 
  Ti Sampled Date[2001-01-01, 2001-01-05] ForwardOrdered Irregular Points
```

For consistency, i also added "Tuple" in the error message shown when using RasterSeries with unsupported `date` or `month` arguments (e.g. only one `Date` : `RasterSeries(AWAP, :solar; date = Date(2001,1,5))`).

**Comment by rafaqz** [comment]
Great! Can you add that example to the AWAP tests? Try to use files downloaded in other tests to minimise the CI downloads.

**Comment by jguerber** [comment]
Done :)

**Comment by rafaqz** [comment]
Julia 1.8 has broken something, I'll have to fix before this can be merged

**Comment by rafaqz** [comment]
Could you rebase this against master and push again now that CI is fixed?

**Comment by jguerber** [comment]
Sure :)

**Pull request merged**
