### PR TITLE
La/new vite docs: ready to merge

### PR DESCRIPTION
**Pull request by lazarusA**
Let's see if CI is working.

### CODE REVIEW

**Comment by lazarusA** [comment]
I don't know why the DD restriction. Locally, is running ok.

**Comment by rafaqz** [comment]
I think the DD problem might be from GitHub actions caching? I had this somewhere else too.

**Comment by asinghvi17** [comment]
If you have admin privileges on the repo, you can delete all caches in the "Actions" tab

**Comment by asinghvi17** [comment]
Looks like UC Davis's server is down again

**Comment by lazarusA** [comment]
good. That fixed the error. But we need to increase the timeout on Downloads. Locally also takes a while. Ideas?

**Comment by felixcremer** [comment]
I added a ` Pkg.Registry.update();` call in the github action. This should solve these problems also in the future. 
See [JuliaDataCubes/YAXArrays.jl@`7474202` (#390)](https://github.com/JuliaDataCubes/YAXArrays.jl/pull/390/commits/74742026f04e200ad941812ebbf76e30c1553d25)

**Comment by rafaqz** [comment]
Ok those are just worldclim/ucdavis outage problems now. 

(We should really purge WorldClim from everything it happens too much)

**Comment by felixcremer** [comment]
The problem with caching is, that this would be redistribution which is allowed only after permission  https://worldclim.org/about.html. When we are using WorldClim as examples, we should find other example datasets that are more reliable or which we could host ourselves.

**Comment by lazarusA** [comment]
@felixcremer @rafaqz any suggestions for a different dataset provider for those examples. So that I can fix this and finish the PR.

**Comment by rafaqz** [comment]
Not sure. WorldClim files are relatively small which helps download time

**Comment by rafaqz** [comment]
Chelsea is a direct replacement, we could use the lowest resolution?

**Comment by lazarusA** [comment]
@rafaqz that should do it. Let's see if data is not longer an issue.

**Comment by rafaqz** [comment]
Now there's a real error ;)

ERROR: LoadError: invalid '@docs' syntax: @docs data_sources

**Comment by lazarusA** [comment]
Ok. Now is a path issue/missing images. The `doctest` creates images, that are not being saved at the right place or rather before they are needed by Vitepress. Will look into this later.

**Comment by asinghvi17** [comment]
│ ERROR: You must set `ENV["RASTERDATASOURCES_PATH"]` to a path in your system

**Comment by lazarusA** [comment]
it is, 
here: https://github.com/rafaqz/Rasters.jl/blob/484cb172e35ccace8bf9106ec0f2d21f381a097c/.github/workflows/Documenter.yml#L47 and 

(twice!)
here: 

https://github.com/rafaqz/Rasters.jl/blob/484cb172e35ccace8bf9106ec0f2d21f381a097c/docs/make.jl#L15

**Comment by lazarusA** [comment]
the error is only for the `doctests`. Really confused now.

**Comment by rafaqz** [comment]
Does the folder exist tho? It won't make one for you

**Comment by lazarusA** [comment]
we r good now: https://rafaqz.github.io/Rasters.jl/previews/PR675/

**Pull request merged**
