### PR TITLE
Update to SDM workflow example in the docs

### PR DESCRIPTION
**Pull request by tiemvanderdeure**
Uses SDM.jl/MLJ to do the whole workflow.

Also updated a few steps that are a lot less clunky now.

(And replaced plots.jl with makie, but feel free to reverse/improve).

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks, looks good

**Comment by tiemvanderdeure** [comment]
Hm I just took a look at the docs and the output of the last cells isn't shown - and it has `@example` in the top right. I must have made some typo?
 billede

**Comment by rafaqz** [comment]
Huh, I can't see anything obvious

**Comment by tiemvanderdeure** [comment]
Same, and it doesn't error either. It could be something with the SDM package as it's unregistered.

**Comment by rafaqz** [comment]
That shouldn't make a difference. I would guess a missing newline or something.

But also that package really wants registering ;)

**Pull request merged**
