### PR TITLE
[WIP] More docs

### PR DESCRIPTION
**Pull request by asinghvi17**
- Switch all references for reproject from GDAL to Proj, improve docstring
- Add Proj to the docs project
- Slightly clarify some doc examples

TODOs:
- [ ] Add official tutorials section with Literate examples
- [ ] Add detailed doc page and exploration of cellarea
- [ ] Add docs about the many ways to change the CRS of a raster
- [ ] Merge in Alex's read/write docs PR here
- [ ] Merge in Lazaro's https://github.com/rafaqz/Rasters.jl/pull/730/ resample PR here.

### CODE REVIEW

**Comment by lazarusA** [comment]
And every method from here should be documented and added to the nav bar.

Screenshot 2024-10-11 at 03 05 26

**Comment by rafaqz** [comment]
Can the nav bar just link to their API docs?

**Comment by asinghvi17** [comment]
Should the cellarea tutorial also show you doing something with it?  Maybe computing average precipitation across Denmark?

**Comment by asinghvi17** [comment]
@rafaqz should we take this local so a preview can be deployed?  I would need write access though.

**Comment by rafaqz** [comment]
>It could but that seems like maintenance hell, best to link to a tutorial I think. The menu bar would also get very long...

I mean putting the links to those methods in the didebar manually. They have pretty extensive documentation with plots etc, best to not do that twice

**Comment by rafaqz** [comment]
Also: I'm not sure about the huge dotpoint PRs. 

Like I like the effort a lot! but it may be better to do what you can, merge it, do a bit more. The checklist can go in an issue? Then it's more democratic and other people can do some of them.

**Comment by asinghvi17** [comment]
Makes sense - I can cut this PR off here and start a new one with the resample/warp docs I have locally.

**Comment by rafaqz** [comment]
Thanks. Just switch it from draft when you need a teview

**Comment by asinghvi17** [comment]
Succeeded by #800

**Pull request closed without merging**
