### PR TITLE
Bump Makie compat

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
If CI passes here, can we merge this and release a new version?  I'm adding some Rasters/GeoMakie examples to GeoMakie, but no currently released version of Rasters is compatible with Makie v0.21.

**Comment by asinghvi17** [comment]
Looks like CI had a segfault somehow?  

```julia

[3106] signal (11.1): Segmentation fault
in expression starting at /home/runner/work/Rasters.jl/Rasters.jl/test/resample.jl:9
ERROR: LoadError: Package Rasters errored during testing (received signal: 11)
```

**Comment by rafaqz** [comment]
Mudt be GDAL

**Comment by lazarusA** [comment]
Yes, for me, things only work with GDAL master. Maybe a new release is in order 🤔

**Pull request closed without merging**
