### PR TITLE
add continue_patch changes more cleanly: fixes Makie for new DD

### PR DESCRIPTION
**Pull request by rafaqz**
supercedes #723 

It was too hard to fix the commit history there!

@lazarusA this should have everything from the other one not already in main

I'll credit you in the quash commit

### CODE REVIEW

**Comment by lazarusA** [comment]
All good 👍.  I also noticed that, but no time to fix. I was also planning,  eventually,  to start from scratch again.

**Comment by rafaqz** [comment]
Ah looks like DD has broken something too

**Comment by lazarusA** [comment]
for docs, is still not getting the latest release of DD. Maybe delete the `cache` for this PR?

**Comment by rafaqz** [comment]
Ah right how do we actually do that again?

**Comment by lazarusA** [comment]
wow! DD is really breaking things up. Next release will be definitely breaking :D

**Comment by rafaqz** [comment]
The equality ones I had earlier will mostly just affect tests and you can turn the off with `strict=false` in `@d` 

But this one now is allocations I. `write`, like type instability? But I can reproduce it at all

**Comment by tiemvanderdeure** [comment]
We added those allocation checks because the eachchunk didn't work and the values were written one by one, which led to millions of allocations. The test only exceeds whatever arbitrary boundary I set by a little bit and only in one place. So while it sure is weird maybe it's okay to just increase it so tests pass, as long as we are sure there is not some serious performance issue.

**Comment by tiemvanderdeure** [comment]
I realized this could be due to julia 1.11?

**Comment by rafaqz** [comment]
Yeah I think so too... Have to update and check type stability

**Pull request merged**
