### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by spaette**
@rafaqz

Note the effect of running the `sed` lines.

If you don't want those changes I will revert them.

```
sed -i "s/isalligned/isaligned/g" Rasters.jl/ext/RastersArchGDALExt/gdal_source.jl
sed -i "s/unalligned/unaligned/g" Rasters.jl/ext/RastersCoordinateTransformationsExt/affineprojected.jl

```

### CODE REVIEW

**Comment by spaette** [comment]
Don't know why the checks failed.

FWIW, the shell script I used to implement the changes.

```
$ cat typos.sh
#!/bin/sh

sed -i "s/Extensts/Extents/g" Rasters.jl/src/methods/burning/extents.jl
sed -i "s/Whithout/Without/g" Rasters.jl/src/lookup.jl
sed -i "s/accross/across/g" Rasters.jl/src/methods/trim.jl
sed -i "s/accrurate/accurate/g" Rasters.jl/test/sources/gdal.jl
sed -i "s/acheive/achieve/g" Rasters.jl/src/methods/burning/polygon.jl
sed -i "s/aggegrated/aggregated/g" Rasters.jl/src/methods/aggregate.jl
sed -i "s/alligned/aligned/g" Rasters.jl/src/methods/reproject.jl
sed -i "s/allways/always/g" Rasters.jl/src/stack.jl
sed -i "s/alocating/allocating/g" Rasters.jl/src/methods/crop_extend.jl
sed -i "s/amound/amount/g" Rasters.jl/src/plotrecipes.jl
sed -i "s/arary/array/g" Rasters.jl/test/array.jl
sed -i "s/doesnt/doesn't/g" Rasters.jl/test/rasterize.jl
sed -i "s/dont/don't/g" Rasters.jl/test/sources/rasterdatasources.jl
sed -i "s/dont/don't/g" Rasters.jl/src/methods/mosaic.jl
sed -i "s/dont/don't/g" Rasters.jl/src/methods/reproject.jl
sed -i "s/dont/don't/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/dont/don't/g" Rasters.jl/src/sources/commondatamodel.jl
sed -i "s/dont/don't/g" Rasters.jl/src/stack.jl
sed -i "s/dont/don't/g" Rasters.jl/src/write.jl
sed -i "s/dont/don't/g" Rasters.jl/docs/make.jl
sed -i "s/dont/don't/g" Rasters.jl/ext/RastersArchGDALExt/gdal_source.jl
sed -i "s/dowloads/downloads/g" Rasters.jl/test/runtests.jl
sed -i "s/enought/enough/g" Rasters.jl/src/methods/coverage.jl
sed -i "s/enourmous/enormous/g" Rasters.jl/src/show.jl
sed -i "s/entrirely/entirely/g" Rasters.jl/src/methods/extract.jl
sed -i "s/erorrs/errors/g" Rasters.jl/src/methods/mosaic.jl
sed -i "s/excessing/excessive/g" Rasters.jl/src/methods/shared_docstrings.jl
sed -i "s/extact/extract/g" Rasters.jl/src/methods/extract.jl
sed -i "s/extenstions/extensions/g" Rasters.jl/src/extensions.jl
sed -i "s/extention/extension/g" Rasters.jl/ext/RastersArchGDALExt/gdal_source.jl
sed -i "s/functin/function/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/gemoetry/geometry/g" Rasters.jl/src/methods/burning/geometry.jl
sed -i "s/geomtry/geometry/g" Rasters.jl/src/methods/coverage.jl
sed -i "s/idenically/identically/g" Rasters.jl/src/series.jl
sed -i "s/immplemented/implemented/g" Rasters.jl/src/sources/commondatamodel.jl
sed -i "s/incrorrect/incorrect/g" Rasters.jl/src/methods/shared_docstrings.jl
sed -i "s/indicies/indices/g" Rasters.jl/src/methods/aggregate.jl
sed -i "s/initiallised/initialised/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/innaccuracy/inaccuracy/g" Rasters.jl/src/methods/mosaic.jl
sed -i "s/innaccurate/inaccurate/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/inorrect/incorrect/g" Rasters.jl/test/sources/gdal.jl
sed -i "s/intead/instead/g" Rasters.jl/src/series.jl
sed -i "s/irrelivent/irrelevant/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/isalligned/isaligned/g" Rasters.jl/ext/RastersArchGDALExt/gdal_source.jl
sed -i "s/layersrom/layersfrom/g" Rasters.jl/src/stack.jl
sed -i "s/nothng/nothing/g" Rasters.jl/src/lookup.jl
sed -i "s/lon alligned/lon aligned/g" Rasters.jl/ext/RastersArchGDALExt/gdal_source.jl
sed -i "s/nothsng/nothing/g" Rasters.jl/src/sources/commondatamodel.jl
sed -i "s/pracice/practice/g" Rasters.jl/src/methods/coverage.jl
sed -i "s/retreive/retrieve/g" Rasters.jl/src/array.jl
sed -i "s/retudcing/reducing/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/retured/returned/g" Rasters.jl/src/methods/extract.jl
sed -i "s/standardisted/standardised/g" Rasters.jl/src/utils.jl
sed -i "s/tolorerance/tolerance/g" Rasters.jl/src/methods/extract.jl
sed -i "s/unalligned/unaligned/g" Rasters.jl/ext/RastersCoordinateTransformationsExt/affineprojected.jl
sed -i "s/variabls/variables/g" Rasters.jl/src/sources/commondatamodel.jl
sed -i "s/whne/when/g" Rasters.jl/src/methods/rasterize.jl
sed -i "s/wraper/wrapper/g" Rasters.jl/src/methods/crop_extend.jl
sed -i "s/wrinting/writing/g" Rasters.jl/src/methods/shared_docstrings.jl
$ 
```

**Comment by rafaqz** [comment]
This is the problem:

```
ERROR: LoadError: UndefVarError: `sliceunaligneddims` not defined
```

**Comment by spaette** [comment]
I should have read the code more thoroughly.

```
$ git clone -q https://github.com/rafaqz/DimensionalData.jl.git
$ grep -nr unalligned DimensionalData.jl | wc -l
19
$ 
```

**Comment by rafaqz** [comment]
Probably we should change those too... But I'll merge these docs changes first

**Comment by spaette** [comment]
I'll take a look at the other repo and open an Issue there.

**Pull request merged**
