### PR TITLE
fix typo in series filename swap

### PR DESCRIPTION
**Pull request by maxfreu**

### CODE REVIEW

**Comment by rafaqz** [comment]
We should test this too

**Comment by maxfreu** [comment]
Yes, but...

I definitely won't be able to do this before end of July. Would be cool to have it merged before that; maybe having an issue for "testing raster series with duplicate_first=true" is an option?

**Comment by rafaqz** [comment]
Ok can you make the issue at least?

**Comment by maxfreu** [comment]
I created the issue. Had to create another one first :cry: :laughing: Thanks for your work!

**Pull request merged**
