### PR TITLE
add `lazy` flag to make laziness optional

### LINKED ISSUE #260: Add `lazy` keyword to constructors
It would be good to be able to turn off DiskArrays.jk lazy loading entirely. We could also set a global variable to define the default value.

Mentioned in #254

### PR DESCRIPTION
**Pull request by rafaqz**
This PR adds a `lazy` flag to `Raster` and `RasterStack` so that lazy loading is optional. For now it is `true` by default, but this may change, or we can add package preference to set it manually.

Closes #260

### CODE REVIEW

**Comment by kongdd** [comment]
glad to see this feature implemented.

**Comment by kongdd** [comment]
I urgently need this feature in one of my recent research. Hope this feature could be in the master branch soon.

**Comment by rafaqz** [comment]
Yeah, there are some problems with CI in RasterDataSources.jl that keep making things fail. Im trying to fix, hopefully tonight.

**Comment by kongdd** [comment]
Awesome. Thank for your help.

**Comment by rafaqz** [comment]
@kongdd see how this goes in CI. I'm pretty busy currently so it might not be tonight unfortunately.

You can also just check out this branch manually if you need it. Like `] add Rasters#lazy`

**Comment by kongdd** [comment]
Got it. Thank u. I will have a try.

**Pull request merged**
