### PR TITLE
Specify source with Symbol and add better filters for url sources

### LINKED ISSUE #406: Feature request: dont check `isfile` for http sources
Since the netCDF library has a builtin capability of lazily reading data from an OPeNDAP server, it would be nice if we can create a `Raster` by something like this:
```julia
using Rasters
url = "http://apdrc.soest.hawaii.edu:80/dods/public_data/" *
  "WOA/WOA18/5_deg/monthly/temp"
varname = "tmn"
rs = Raster(url; name = varname, dataformat=:netcdf)
```
Rafael Schouten said in [Julia discourse](https://discourse.julialang.org/t/create-a-raster-from-opendap-netcdf/96756/2):
> The first problem is there is no way to tell this is a NetCDF and you should use the NCDatasets.jl backend, as there is no .nc extension. So you need to use source=Rasters.NCDfile.
> But then there is a check for if the file exists, and of course that fails.
> What we should do is skip file checks if the path starts with `http` and similar.

But,  in the future, there may be other data formats that use the HTTP protocol to represent remote data.  So, wouldn't an optional argument such as `dataformat=:netcdf` be more extensible? 

Also, that would help this situation:
```julia
rs = Raster("tmp.cdf"; name = "slp", dataformat=:netcdf)
```
There are still ancient netCDF files around that use the old extension `.cdf`.

### PR DESCRIPTION
**Pull request by rafaqz**
Allows using `Symbol` for sources, e.g. `:gdal` and `:netcdf` - which are much more obvious and don't need to be exported.

Also skips `isfile` checks when sources are online, and reorganises the sources code a little.

Closes #406 

@ryofurue do you want to try out this branch and see if it works for you?

```julia
using Rasters
url = "http://apdrc.soest.hawaii.edu:80/dods/public_data/" * "WOA/WOA18/5_deg/monthly/temp"
rs = Raster(url; name=:tmn, source=:netcdf, lazy=true)
...
Note:Caching=1
72×36×57×12 Raster{Union{Missing, Float32},4} tmn with dimensions: 
  X Mapped{Float64} Float64[-177.5, -172.5, …, 172.5, 177.5] ForwardOrdered Regular Points,
  Y Mapped{Float64} Float64[-87.5, -82.5, …, 82.5, 87.5] ForwardOrdered Regular Points,
  Z Sampled{Float64} Float64[0.0, 5.0, …, 1450.0, 1500.0] ForwardOrdered Irregular Points,
  Ti Sampled{DateTime} DateTime[0000-01-13T00:00:00, …, 0000-12-13T00:00:00] ForwardOrdered Irregular Points
extent: Extent(X = (-177.5, 177.5), Y = (-87.5, 87.5), Z = (0.0, 1500.0), Ti = (DateTime("0000-01-13T00:00:00"), DateTime("0000-12-13T00:00:00")))
missingval: missing
from file:
http://apdrc.soest.hawaii.edu:80/dods/public_data/WOA/WOA18/5_deg/monthly/temp
```

Note you need `lazy=true` for this to work well, or it will download the whole thing up front.

Indexing into it will materialize the array:

```julia
julia> slice = rs[Z(1), Ti(1)]
Note:Caching=1
72×36 Raster{Union{Missing, Float32},2} tmn with dimensions: 
  X Mapped{Float64} Float64[-177.5, -172.5, …, 172.5, 177.5] ForwardOrdered Regular Points,
  Y Mapped{Float64} Float64[-87.5, -82.5, …, 82.5, 87.5] ForwardOrdered Regular Points
and reference dimensions: 
  Z Sampled{Float64} Float64[0.0] ForwardOrdered Irregular Points,
  Ti Sampled{DateTime} DateTime[DateTime("0000-01-13T00:00:00")] ForwardOrdered Irregular Points
extent: Extent(X = (-177.5, 177.5), Y = (-87.5, 87.5))
missingval: missing
parent:
         -87.5       -82.5       -77.5        -72.5       -67.5        -62.5      -57.5      -52.5      …  47.5      52.5      57.5       62.5       67.5       72.5       77.5       82.5       87.5
 -177.5     missing     missing   -0.610712    -0.758991    0.0220078    3.0381     6.05157    9.95598      4.65429   3.62802   2.68207    2.07794     missing    missing    missing  -1.61        missing
 -172.5     missing     missing   -0.655066    -0.837662   -0.200933     2.30841    5.88205   10.166        5.04545   3.78979   2.63994   -0.12511     missing    missing    missing    missing  -1.6225
 -167.5     missing     missing   -0.600787    -1.10766    -0.319929     2.07657    5.80034    9.58763      5.16739   4.0673    3.02232   -0.101749    missing  -1.56        missing    missing    missing
    ⋮                                                       ⋮                                           ⋱                       ⋮                                                      ⋮         
  162.5     missing     missing     missing      missing   -0.248663     2.42037    4.21011    9.50032  …   2.24009   2.71454    missing    missing    missing    missing    missing  -1.66188     missing
  167.5     missing     missing    0.205162      missing   -0.3679       2.74865    6.49567   10.3362       3.29061   3.01577   0.977937    missing    missing  -1.6         missing    missing    missing
  172.5     missing     missing   -0.0310046   -0.446999   -0.520175     2.41964    6.51768    8.88811      4.12297   3.72483   1.91544     missing    missing  -1.5875      missing    missing  -1.6047
  177.5     missing     missing   -0.506007    -0.557469   -0.383888     2.99873    6.36641    8.32075      4.75219   3.7676    2.10948    1.01813     missing    missing    missing  -1.623       missing
```

@tcarion note this might clash with your PR a little, not the move to sources/sources.jl of all the source related code

### CODE REVIEW

**Comment by ryofurue** [comment]
@rafaqz Thank you very much for your help and I'm very sorry for my silence.  I've been quite occupied with other things and I missed your query

> @ryofurue do you want to try out this branch and see if it works for you?

Yes, I'd like to try a version that includes the capability of reading online netCDF, but I'm not sure when I will start that.  On the other hand,  if you need a tester now, I will definitely help you now.

**Comment by rafaqz** [comment]
No worries! Since this PR was mostly in response to your feature requests, I was offering you to comment/try (even review the code) to make sure it actually solves your problems.

Whatever you have time for, but it's good to have some quality control.

**Comment by ryofurue** [comment]
Belatedly, I've just started to work on a remote dataset via the OPeNDAP protocol again.  What is the current status of `Rasters` ?  The code at the bottom of this message gives the following error message.  I tried to use a remote dataset by `Raster(url; name="mslp", source=Rasters.NCDfile)`. I'm using `Rasters v0.7.2` on `julia 1.9.0` on macOS 13.4. (I constantly update everything via `juliaup`.)  I've confirmed that the remote data can be used via the `NCDatasets` package (see the commented-out code).

```julia
ERROR: LoadError: MethodError: no method matching _open(::Type{Array}, ::Type{Rasters.GDALsource}, ::CommonDataModel.CFVariable{Union{Missing, Float32}, 3, NCDatasets.Variable{Float32, 3, NCDataset{Nothing}}, NCDatasets.Attributes{NCDataset{Nothing}}, NamedTuple{(:fillvalue, :missing_values, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor), Tuple{Float32, Tuple{Float32}, Vararg{Nothing, 5}}}}; key::String)

Closest candidates are:
  _open(::Any, ::Type{Rasters.NCDsource}, ::CommonDataModel.CFVariable; kw...)
   @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:248
  _open(::Any, ::Type{Rasters.GDALsource}, ::AbstractString; write, kw...)
   @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/gdal.jl:128
  _open(::Any, ::Type{Rasters.GDALsource}, ::ArchGDAL.RasterDataset; kw...)
   @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/gdal.jl:144
  ...

Stacktrace:
  [1] Raster(ds::CommonDataModel.CFVariable{Union{Missing, Float32}, 3, NCDatasets.Variable{Float32, 3, NCDataset{Nothing}}, NCDatasets.Attributes{NCDataset{Nothing}}, NamedTuple{(:fillvalue, :missing_values, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor), Tuple{Float32, Tuple{Float32}, Vararg{Nothing, 5}}}}, filename::String, key::String; crs::Nothing, mappedcrs::Nothing, dims::Nothing, refdims::Tuple{}, name::Symbol, metadata::DimensionalData.Dimensions.LookupArrays.Metadata{Rasters.NCDsource, Dict{String, Any}}, missingval::Missing, source::Nothing, write::Bool, lazy::Bool, dropband::Bool)
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/array.jl:321
  [2] Raster(ds::CommonDataModel.CFVariable{Union{Missing, Float32}, 3, NCDatasets.Variable{Float32, 3, NCDataset{Nothing}}, NCDatasets.Attributes{NCDataset{Nothing}}, NamedTuple{(:fillvalue, :missing_values, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor), Tuple{Float32, Tuple{Float32}, Vararg{Nothing, 5}}}}, filename::String, key::String)
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/array.jl:308
  [3] Raster(ds::NCDataset{Nothing}, filename::String, key::String; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:57
  [4] Raster(ds::NCDataset{Nothing}, filename::String, key::String)
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:46
  [5] (::Rasters.var"#61#62"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, String})(ds::NCDataset{Nothing})
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/array.jl:305
  [6] _open(f::Rasters.var"#61#62"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, String}, ::Type{Rasters.NCDsource}, ds::NCDataset{Nothing}; key::Nothing, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:246
  [7] _open
    @ ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:244 [inlined]
  [8] #911
    @ ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:241 [inlined]
  [9] NCDataset(::Rasters.var"#911#912"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Rasters.var"#61#62"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, String}}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ NCDatasets ~/.julia/packages/NCDatasets/AHGbP/src/dataset.jl:255
 [10] NCDataset(::Function, ::String, ::Vararg{String})
    @ NCDatasets ~/.julia/packages/NCDatasets/AHGbP/src/dataset.jl:252
 [11] #_open#910
    @ ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:240 [inlined]
 [12] _open(f::Function, ::Type{Rasters.NCDsource}, filename::String)
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/ncdatasets.jl:237
 [13] _open(f::Function, filename::String; source::Type, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/sources/sources.jl:52
 [14] _open
    @ ~/.julia/packages/Rasters/0lwLA/src/sources/sources.jl:51 [inlined]
 [15] Raster(filename::String; name::String, key::String, source::Type, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Rasters ~/.julia/packages/Rasters/0lwLA/src/array.jl:303
 [16] top-level scope
    @ ~/Dropbox/fukao/typhoons/utils/try-opendap.jl:17
 [17] include(fname::String)
    @ Base.MainInclude ./client.jl:478
 [18] top-level scope
    @ REPL[1]:1
in expression starting at /Users/furue/Dropbox/fukao/typhoons/utils/try-opendap.jl:17
```

```julia
using NCDatasets
using Rasters
using Plots

url = "http://apdrc.soest.hawaii.edu:80/dods/public_data/" *
  "Reanalysis_Data/NCEP/NCEP2/daily/surface/mslp"

#==
ds = NCDataset(url)
mslp = ds["mslp"]
lon = ds["lon"]
lat = ds["lat"]
contour(lon,lat,transpose(mslp[:,:,10]))
close(ds)
==#

r = Raster(url; name="mslp", source=Rasters.NCDfile)
```

**Comment by rafaqz** [comment]
Best to put this in a real ossue so ots visible. It looks like NCDatasets has made breakinh changes in a minor version, but I will need to check.

**Comment by rafaqz** [comment]
Best to put this in a real ossue so ots visible. 

(Actually thay looks like source is not propagating? You can also do `source=:netcdf` now)

**Comment by rafaqz** [comment]
There have been a bunch of changes to this syuff, `NCDfile` is depracated fir `NCDsource` abd just using `:netcdf`. But I may have broken something.

**Pull request merged**
