### PR TITLE
Add get_scale definition to GRIBDatasetsExt

### PR DESCRIPTION
**Pull request by asinghvi17**
Same as for ZarrDatasetsExt.  Needs a test with a grib file.

### CODE REVIEW

**Comment by asinghvi17** [comment]
all the segfaults from GDAL, lol...

**Comment by rafaqz** [comment]
Aah it's GDAL warp segfaulting I was hoping it would just go away 

 @visr do you have an idea what's going on there? Has anything obvious changed in the GDAL side?

**Comment by visr** [comment]
Hmm strange. The GDAL build was broken last week: https://github.com/JuliaGeo/GDAL.jl/issues/179
So two new builds were released: https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases
It looks like you are on the latest release. Can you easily try [301.901.201](https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/tag/GDAL-v301.901.201%2B0)? Then we could narrow it down. The GDAL 3.9.3 release that came out today also lists two gdalwarp improvements, though this looks more like a regression: https://github.com/OSGeo/gdal/blob/v3.9.3/NEWS.md

We should also fix the Rasters.jl GDAL.jl integration tests again. I haven't looked at them much since they've been red since the beginning.

**Comment by visr** [comment]
So it seems from #806 that GDAL_jll v301.901.201 works ok but v301.902.200 segfaults on gdalwarp, but otherwise seems functional?

**Comment by rafaqz** [comment]
Yeah, all the other GDAL tests are passing.

**Comment by visr** [comment]
Might be a GDAL issue then, not a build failure. Though you could still try the latest GDAL patch release that came out today in the GDAL_jll. Not sure which of the gdalwarp tests is segfaulting. GDAL.jl does have a basic gdalwarp test as well, not as many variations as Rasters.jl though.

**Comment by rafaqz** [comment]
Was there a test for this?

**Pull request merged**
